#!/bin/sh

set -e

case "$1" in
    configure)
        if ! getent passwd _clevis >/dev/null; then
            adduser --quiet --system --group --no-create-home --home /nonexistent --force-badname _clevis
        fi
        ;;
    abort-upgrade | abort-remove | abort-deconfigure) ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
exit 0
